export const countryCollections = {
  'Australia': [
    { title: 'Australia, Victoria, Coastal Passenger Lists, 1852-1924', desc: '3,244,620 records', description: 'Passenger arrival and departure records', link: 'https://www.familysearch.org/en/search/collection/2484773', icon: icons.immigration },
    { title: 'Australia, Victoria, Petty Sessions Registers, 1858-1985', desc: '3,095,843 records', description: 'Historical records and documents', link: 'https://www.familysearch.org/en/search/collection/2485052', icon: icons.historical },
    { title: 'Australia, Queensland, Cemetery Records, 1802-1990', desc: '2,168,403 records', description: 'Cemetery and burial records', link: 'https://www.familysearch.org/en/search/collection/1927198', icon: icons.historical },
    { title: 'Australia, Victoria, Outward Passenger Lists, 1852-1924', desc: '1,862,984 records', description: 'Passenger arrival and departure records', link: 'https://www.familysearch.org/en/search/collection/2527519', icon: icons.immigration },
    { title: 'Australia, Cemetery Inscriptions, 1802-2005', desc: '1,124,406 records', description: 'Cemetery and burial records', link: 'https://www.familysearch.org/en/search/collection/2115584', icon: icons.historical },
  ],
  'Brazil': [
    { title: 'Brazil, Rio de Janeiro, Civil Registration, 1804-2013', desc: '6,379,080 records', description: 'Birth, marriage, and death certificates', link: 'https://www.familysearch.org/en/search/collection/1582573', icon: icons.civil },
    { title: 'Brazil, São Paulo, Civil Registration, 1925-2023', desc: '4,486,374 records', description: 'Birth, marriage, and death certificates', link: 'https://www.familysearch.org/en/search/collection/2765317', icon: icons.civil },
    { title: 'Brazil, Cemetery Records, 1799-2024', desc: '4,414,028 records', description: 'Cemetery and burial records', link: 'https://www.familysearch.org/en/search/collection/2137269', icon: icons.historical },
    { title: 'Brazil, São Paulo, Catholic Church Records, 1640-2013', desc: '4,018,558 records', description: 'Baptisms, marriages, and burials', link: 'https://www.familysearch.org/en/search/collection/2177299', icon: icons.church },
    { title: 'Brazil, Pernambuco, Catholic Church Records, 1762-2019', desc: '2,631,795 records', description: 'Baptisms, marriages, and burials', link: 'https://www.familysearch.org/en/search/collection/2177293', icon: icons.church },
  ],
  'Canada': [
    { title: 'Canada, Census, 1911', desc: '7,246,159 records', description: 'Population schedules and enumeration data', link: 'https://www.familysearch.org/en/search/collection/2143998', icon: icons.census },
    { title: 'Canada, Ontario, Tax Assessment Rolls, 1827-1922', desc: '6,231,709 records', description: 'Tax assessment records', link: 'https://www.familysearch.org/en/search/collection/4130007', icon: icons.census },
    { title: 'Canada, Census, 1901', desc: '5,343,565 records', description: 'Population schedules and enumeration data', link: 'https://www.familysearch.org/en/search/collection/1584557', icon: icons.census },
    { title: 'Canada, Census, 1891', desc: '4,787,225 records', description: 'Population schedules and enumeration data', link: 'https://www.familysearch.org/en/search/collection/1583536', icon: icons.census },
    { title: 'Canada, Census, 1881', desc: '4,281,160 records', description: 'Population schedules and enumeration data', link: 'https://www.familysearch.org/en/search/collection/1804541', icon: icons.census },
  ],
  'China': [
    { title: 'China, Imperial Examinations and Related Papers (Han Yu-shan Collection), 1646-1904', desc: '455 records', description: 'Historical records and documents', link: 'https://www.familysearch.org/en/search/collection/2490249', icon: icons.historical },
    { title: 'China, Cemetery Records, 1820-1983', desc: 'Browse Images', description: 'Cemetery and burial records', link: 'https://www.familysearch.org/en/search/collection/2128186', icon: icons.historical },
  ],
  'England': [
    { title: 'England and Wales, Birth Registration Index, 1837-2008', desc: '132,174,239 records', description: 'Birth registration records', link: 'https://www.familysearch.org/en/search/collection/2285338', icon: icons.civil },
    { title: 'England and Wales, Marriage Registration Index, 1837-2005', desc: '95,810,879 records', description: 'Marriage registration records', link: 'https://www.familysearch.org/en/search/collection/2285732', icon: icons.church },
    { title: 'England and Wales, Death Registration Index 1837-2007', desc: '87,446,270 records', description: 'Death registration records', link: 'https://www.familysearch.org/en/search/collection/2285341', icon: icons.civil },
    { title: 'England, Births and Christenings, 1538-1975', desc: '40,718,182 records', description: 'Church baptismal records', link: 'https://www.familysearch.org/en/search/collection/1473014', icon: icons.church },
    { title: 'England and Wales, Census, 1911', desc: '36,354,828 records', description: 'Population schedules and enumeration data', link: 'https://www.familysearch.org/en/search/collection/1921547', icon: icons.census },
  ],
  'Germany': [
    { title: 'Germany, Lutheran Baptisms, Marriages, and Burials, 1500-1971', desc: '76,097,837 records', description: 'Church baptismal records', link: 'https://www.familysearch.org/en/search/collection/3015626', icon: icons.church },
    { title: 'Germany, Births and Baptisms, 1558-1898', desc: '24,603,619 records', description: 'Church baptismal records', link: 'https://www.familysearch.org/en/search/collection/1473000', icon: icons.church },
    { title: 'Germany, Prussia, Posen, Catholic and Lutheran Church Records, 1430-1998', desc: '12,831,327 records', description: 'Lutheran parish registers', link: 'https://www.familysearch.org/en/search/collection/4116415', icon: icons.church },
    { title: 'Germany, Baden, Archdiocese of Freiburg im Breisgau, Catholic Church Records, 1463-1931', desc: '11,346,687 records', description: 'Baptisms, marriages, and burials', link: 'https://www.familysearch.org/en/search/collection/2790181', icon: icons.church },
    { title: 'Germany, Prussia, West Prussia, Catholic and Lutheran Church Records, 1537-1981', desc: '10,009,338 records', description: 'Lutheran parish registers', link: 'https://www.familysearch.org/en/search/collection/4111605', icon: icons.church },
  ],
  'Ireland': [
    { title: 'Ireland, Petty Sessions Court Registers, 1828-1912', desc: '21,724,267 records', description: 'Court records and legal proceedings', link: 'https://www.familysearch.org/en/search/collection/2487287', icon: icons.historical },
    { title: 'Ireland, Civil Registration Indexes, 1845-1958', desc: '18,958,897 records', description: 'Birth, marriage, and death certificates', link: 'https://www.familysearch.org/en/search/collection/1408347', icon: icons.civil },
    { title: 'Ireland, Catholic Parish Registers, 1740-1900', desc: '9,535,478 records', description: 'Baptisms, marriages, and burials', link: 'https://www.familysearch.org/en/search/collection/2820100', icon: icons.church },
    { title: 'Ireland, Valuation Office Books, 1831-1856', desc: '7,284,359 records', description: 'Historical records and documents', link: 'https://www.familysearch.org/en/search/collection/2329951', icon: icons.historical },
    { title: 'Ireland, Dog License Registrations, 1810-1926', desc: '7,270,375 records', description: 'Historical records and documents', link: 'https://www.familysearch.org/en/search/collection/5000212', icon: icons.historical },
  ],
  'Italy': [
    { title: 'Italy, Bari, Civil Registration (State Archive), 1809-1908', desc: '7,593,992 records', description: 'Birth, marriage, and death certificates', link: 'https://www.familysearch.org/en/search/collection/1968511', icon: icons.civil },
    { title: 'Italy, Toscana, Civil Registration (State Archive), 1804-1874', desc: '6,732,218 records', description: 'Birth, marriage, and death certificates', link: 'https://www.familysearch.org/en/search/collection/1932364', icon: icons.civil },
    { title: 'Italy, Napoli, Civil Registration (State Archive), 1809-1866', desc: '5,113,220 records', description: 'Birth, marriage, and death certificates', link: 'https://www.familysearch.org/en/search/collection/1937990', icon: icons.civil },
    { title: 'Italy, Salerno, Civil Registration (State Archive), 1806-1949', desc: '4,563,213 records', description: 'Birth, marriage, and death certificates', link: 'https://www.familysearch.org/en/search/collection/1935404', icon: icons.civil },
    { title: 'Italy, Torino, Torino, Civil Registration (Tribunale), 1866-1899', desc: '3,631,222 records', description: 'Birth, marriage, and death certificates', link: 'https://www.familysearch.org/en/search/collection/1967801', icon: icons.civil },
  ],
  'Japan': [
    { title: 'Japan, Emigration Records, 1893-1941', desc: '49,794 records', description: 'Emigration records', link: 'https://www.familysearch.org/en/search/collection/1803988', icon: icons.immigration },
    { title: 'Japan, Census Records, 1661-1875', desc: 'Browse Images', description: 'Population schedules and enumeration data', link: 'https://www.familysearch.org/en/search/collection/2313184', icon: icons.census },
    { title: 'Japan, Genealogies, 850-2012', desc: 'Browse Images', description: 'Historical records and documents', link: 'https://www.familysearch.org/en/search/collection/1919701', icon: icons.historical },
    { title: 'Japan, Village Records, 709-1982', desc: 'Browse Images', description: 'Historical records and documents', link: 'https://www.familysearch.org/en/search/collection/1398719', icon: icons.historical },
  ],
  'Korea': [
    { title: 'Korea, Civil Service Examinations and Records of Officials and Employees, 1390-1900', desc: 'Browse Images', description: 'Historical records and documents', link: 'https://www.familysearch.org/en/search/collection/2316009', icon: icons.historical },
    { title: 'Korea, Collection of Genealogies, 1200-2014', desc: 'Browse Images', description: 'Historical records and documents', link: 'https://www.familysearch.org/en/search/collection/1398522', icon: icons.historical },
    { title: 'Korea, Encyclopedias and Dictionaries, 1500-2000', desc: 'Browse Images', description: 'Historical records and documents', link: 'https://www.familysearch.org/en/search/collection/2556015', icon: icons.historical },
    { title: 'Korea, Local History, 655-1935', desc: 'Browse Images', description: 'Historical records and documents', link: 'https://www.familysearch.org/en/search/collection/2556017', icon: icons.historical },
    { title: 'Korea, School Records, 1958', desc: 'Browse Images', description: 'Historical records and documents', link: 'https://www.familysearch.org/en/search/collection/2556024', icon: icons.historical },
  ],
  'Mexico': [
    { title: 'Mexico, Baptisms, 1560-1950', desc: '29,523,755 records', description: 'Church baptismal records', link: 'https://www.familysearch.org/en/search/collection/1473011', icon: icons.church },
    { title: 'Mexico, Guanajuato, Catholic Church Records, 1519-1984', desc: '11,057,682 records', description: 'Baptisms, marriages, and burials', link: 'https://www.familysearch.org/en/search/collection/1860831', icon: icons.church },
    { title: 'Mexico, México, Catholic Church Records, 1567-1970', desc: '8,394,844 records', description: 'Baptisms, marriages, and burials', link: 'https://www.familysearch.org/en/search/collection/1837908', icon: icons.church },
    { title: 'Mexico, Jalisco, Catholic Church Records, 1590-2022', desc: '8,350,860 records', description: 'Baptisms, marriages, and burials', link: 'https://www.familysearch.org/en/search/collection/1874591', icon: icons.church },
    { title: 'Mexico, Jalisco, Civil Registration, 1857-2000', desc: '7,166,874 records', description: 'Birth, marriage, and death certificates', link: 'https://www.familysearch.org/en/search/collection/1918187', icon: icons.civil },
  ],
  'New Zealand': [
    { title: 'New Zealand, Electoral Rolls, 1865-1957', desc: '12,309,008 records', description: 'Electoral rolls and voter registrations', link: 'https://www.familysearch.org/en/search/collection/3662227', icon: icons.census },
    { title: 'New Zealand, Archives New Zealand, Passenger Lists, 1839-1974', desc: '7,264,551 records', description: 'Passenger arrival and departure records', link: 'https://www.familysearch.org/en/search/collection/1609792', icon: icons.immigration },
    { title: 'New Zealand, Obituaries, 1844-1963', desc: '1,768,692 records', description: 'Obituary records', link: 'https://www.familysearch.org/en/search/collection/2538222', icon: icons.historical },
    { title: 'New Zealand, Civil Records Indexes, 1800-1966', desc: '1,758,729 records', description: 'Historical records and documents', link: 'https://www.familysearch.org/en/search/collection/2697870', icon: icons.historical },
    { title: 'New Zealand, Cemetery Transcriptions, 1835-2006', desc: '417,004 records', description: 'Cemetery and burial records', link: 'https://www.familysearch.org/en/search/collection/2780088', icon: icons.historical },
  ],
  'Northern Ireland': [
    { title: 'Northern Ireland, Tithe Applotment Books, 1822-1840', desc: '397,856 records', description: 'Historical records and documents', link: 'https://www.familysearch.org/en/search/collection/2729531', icon: icons.historical },
    { title: 'Northern Ireland, Death Records, 1998-2015', desc: '72,539 records', description: 'Historical records and documents', link: 'https://www.familysearch.org/en/search/collection/4441751', icon: icons.historical },
  ],
  'Norway': [
    { title: 'Norway, Church Books, 1797-1958', desc: '14,398,439 records', description: 'Historical records and documents', link: 'https://www.familysearch.org/en/search/collection/4237104', icon: icons.church },
    { title: 'Norway, Baptisms, 1634-1927', desc: '5,277,294 records', description: 'Church baptismal records', link: 'https://www.familysearch.org/en/search/collection/1467014', icon: icons.church },
    { title: 'Norway, Census, 1891', desc: '2,727,197 records', description: 'Population schedules and enumeration data', link: 'https://www.familysearch.org/en/search/collection/4067726', icon: icons.census },
    { title: 'Norway, Census, 1900', desc: '2,260,720 records', description: 'Population schedules and enumeration data', link: 'https://www.familysearch.org/en/search/collection/3744863', icon: icons.census },
    { title: 'Norway, Census, 1865', desc: '1,688,075 records', description: 'Population schedules and enumeration data', link: 'https://www.familysearch.org/en/search/collection/3756102', icon: icons.census },
  ],
  'Philippines': [
    { title: 'Philippines, Catholic Church Records, 1520-2014', desc: '12,213,164 records', description: 'Baptisms, marriages, and burials', link: 'https://www.familysearch.org/en/search/collection/2861657', icon: icons.church },
    { title: 'Philippines Civil Registration (National), 1945-1996', desc: '5,264,264 records', description: 'Birth, marriage, and death certificates', link: 'https://www.familysearch.org/en/search/collection/1852584', icon: icons.civil },
    { title: 'Philippines, Neighborhood Census, 1836-1899', desc: '4,388,414 records', description: 'Population schedules and enumeration data', link: 'https://www.familysearch.org/en/search/collection/5000268', icon: icons.census },
    { title: 'Philippines, Church Census, 1542-1980', desc: '4,340,954 records', description: 'Population schedules and enumeration data', link: 'https://www.familysearch.org/en/search/collection/5000216', icon: icons.church },
    { title: 'Philippines, Deaths and Burials, 1726-1998', desc: '2,781,591 records', description: 'Historical records and documents', link: 'https://www.familysearch.org/en/search/collection/1500714', icon: icons.church },
  ],
  'Portugal': [
    { title: 'Portugal, Lisbon, Catholic Church Records, 1334-1998', desc: '3,203,007 records', description: 'Baptisms, marriages, and burials', link: 'https://www.familysearch.org/en/search/collection/4449050', icon: icons.church },
    { title: 'Portugal, Porto, Catholic Church Records, 1535-2006', desc: '2,768,292 records', description: 'Baptisms, marriages, and burials', link: 'https://www.familysearch.org/en/search/collection/1913408', icon: icons.church },
    { title: 'Portugal, Viseu, Catholic Church Records, 1523-1989', desc: '2,163,002 records', description: 'Baptisms, marriages, and burials', link: 'https://www.familysearch.org/en/search/collection/1928589', icon: icons.church },
    { title: 'Portugal, Portalegre, Catholic Church Records, 1532-1928', desc: '2,077,104 records', description: 'Baptisms, marriages, and burials', link: 'https://www.familysearch.org/en/search/collection/2014755', icon: icons.church },
    { title: 'Portugal, Coimbra, Catholic Church Records, 1459-1999', desc: '2,022,959 records', description: 'Baptisms, marriages, and burials', link: 'https://www.familysearch.org/en/search/collection/1928593', icon: icons.church },
  ],
  'Scotland': [
    { title: 'Scotland, Births and Baptisms, 1564-1950', desc: '8,079,105 records', description: 'Church baptismal records', link: 'https://www.familysearch.org/en/search/collection/1771030', icon: icons.church },
    { title: 'Scotland, Civil Registration, 1855-1875, 1881, 1891', desc: '5,147,127 records', description: 'Birth, marriage, and death certificates', link: 'https://www.familysearch.org/en/search/collection/5000163', icon: icons.civil },
    { title: 'Scotland, Marriages, 1561-1910', desc: '1,999,716 records', description: 'Historical records and documents', link: 'https://www.familysearch.org/en/search/collection/1771074', icon: icons.church },
    { title: 'Scotland, Death Records,1998-2015', desc: '429,095 records', description: 'Historical records and documents', link: 'https://www.familysearch.org/en/search/collection/4441753', icon: icons.historical },
    { title: 'Scotland, Church Records and Kirk Session Records, 1658-1919', desc: '227,382 records', description: 'Historical records and documents', link: 'https://www.familysearch.org/en/search/collection/2390848', icon: icons.church },
  ],
  'South Africa': [
    { title: 'South Africa, Dutch Reformed Church Registers (Cape Town Archives), 1660-1994 ', desc: '3,030,218 records', description: 'Historical records and documents', link: 'https://www.familysearch.org/en/search/collection/1478678', icon: icons.church },
    { title: 'South Africa, Cape Province, Civil Records, 1840-1972', desc: '2,800,824 records', description: 'Historical records and documents', link: 'https://www.familysearch.org/en/search/collection/1779109', icon: icons.historical },
    { title: 'South Africa, Civil Marriage Records, 1801-1974', desc: '2,557,010 records', description: 'Historical records and documents', link: 'https://www.familysearch.org/en/search/collection/2821281', icon: icons.church },
    { title: 'South Africa, Gauteng, Johannesburg, Cemetery Records, 1840-2019', desc: '2,272,299 records', description: 'Cemetery and burial records', link: 'https://www.familysearch.org/en/search/collection/4453927', icon: icons.historical },
    { title: 'South Africa, Cape, Probate Records of the Master of the High Court, 1822-1990', desc: '2,014,794 records', description: 'Court records and legal proceedings', link: 'https://www.familysearch.org/en/search/collection/2517051', icon: icons.historical },
  ],
  'Spain': [
    { title: 'Spain, Catholic Church Records, 1307-2005', desc: '18,518,441 records', description: 'Baptisms, marriages, and burials', link: 'https://www.familysearch.org/en/search/collection/1784529', icon: icons.church },
    { title: 'Spain, Baptisms, 1502-1940', desc: '8,173,079 records', description: 'Church baptismal records', link: 'https://www.familysearch.org/en/search/collection/1500692', icon: icons.church },
    { title: 'Spain, Aragón, Electoral Censuses, 1890-1955', desc: '4,972,408 records', description: 'Population schedules and enumeration data', link: 'https://www.familysearch.org/en/search/collection/2304578', icon: icons.census },
    { title: 'Spain, Diocese of Cartagena, Catholic Church Records, 1503-1969', desc: '2,445,160 records', description: 'Baptisms, marriages, and burials', link: 'https://www.familysearch.org/en/search/collection/2345225', icon: icons.church },
    { title: 'Spain, Marriages, 1565-1950', desc: '2,269,515 records', description: 'Historical records and documents', link: 'https://www.familysearch.org/en/search/collection/1500693', icon: icons.church },
  ],
  'United States': [
    { title: 'United States, Public Records, 1970-2009', desc: '875,600,997 records', description: 'Historical records and documents', link: 'https://www.familysearch.org/en/search/collection/2199956', icon: icons.historical },
    { title: 'United States, Residence Database, 1970-2024', desc: '413,859,609 records', description: 'Historical records and documents', link: 'https://www.familysearch.org/en/search/collection/5000290', icon: icons.historical },
    { title: 'United States, Census, 1950', desc: '157,892,854 records', description: 'Population schedules and enumeration data', link: 'https://www.familysearch.org/en/search/collection/4464515', icon: icons.census },
    { title: 'United States, Census, 1940', desc: '134,774,707 records', description: 'Population schedules and enumeration data', link: 'https://www.familysearch.org/en/search/collection/2000219', icon: icons.census },
    { title: 'United States, Census, 1930', desc: '125,136,392 records', description: 'Population schedules and enumeration data', link: 'https://www.familysearch.org/en/search/collection/1810731', icon: icons.census },
  ],
  'Wales': [
    { title: 'Wales, Glamorgan, West Glamorgan, Electoral Registers, 1839-1925', desc: '1,643,483 records', description: 'Electoral rolls and voter registrations', link: 'https://www.familysearch.org/en/search/collection/1546473', icon: icons.census },
    { title: 'Wales, Glamorgan Parish Registers, 1558-1900', desc: '921,889 records', description: 'Baptisms, marriages, and burials', link: 'https://www.familysearch.org/en/search/collection/1952632', icon: icons.church },
    { title: 'Wales, Glamorganshire, Parish Registers, 1538-1912', desc: '731,146 records', description: 'Baptisms, marriages, and burials', link: 'https://www.familysearch.org/en/search/collection/2075047', icon: icons.church },
    { title: 'Wales, Births and Baptisms, 1541-1907', desc: '686,084 records', description: 'Church baptismal records', link: 'https://www.familysearch.org/en/search/collection/1783957', icon: icons.church },
    { title: 'Wales, Denbighshire, Parish Registers, 1538-1912', desc: '685,838 records', description: 'Baptisms, marriages, and burials', link: 'https://www.familysearch.org/en/search/collection/1419318', icon: icons.church },
  ],
};